import React, { useState, useRef, useEffect } from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function LegalDisclosure({ onAccept }) {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const contentRef = useRef(null);

  const handleScroll = (e) => {
    const element = e.target;
    const bottom = Math.abs(element.scrollHeight - element.scrollTop - element.clientHeight) < 5;
    if (bottom && !hasScrolledToBottom) {
      setHasScrolledToBottom(true);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4">
      <Card className="max-w-2xl w-full max-h-[90vh] flex flex-col">
        <CardHeader>
          <CardTitle className="text-2xl text-center text-red-600">
            ⚠️ Legal Disclaimer & Terms of Use
          </CardTitle>
        </CardHeader>
        <CardContent className="flex-1 flex flex-col">
          <div
            ref={contentRef}
            onScroll={handleScroll}
            className="overflow-y-auto border border-gray-300 rounded-lg p-4 mb-4 bg-gray-50 max-h-[60vh]"
          >
            <div className="space-y-4 text-sm text-gray-800">
              <p className="font-bold text-lg text-center">
                PLEASE READ THIS DISCLAIMER CAREFULLY BEFORE USING THIS APPLICATION
              </p>

              <p className="font-semibold">USE AT YOUR OWN RISK</p>
              <p>
                By using the Kibble Analyzer App (the "App"), you acknowledge and agree that you are using this application entirely at your own discretion and risk. The information, analysis, recommendations, and content provided by this App are for general informational and educational purposes only.
              </p>

              <p className="font-semibold">NOT VETERINARY ADVICE</p>
              <p>
                This App does not provide veterinary medical advice, diagnosis, or treatment. The nutritional analysis and recommendations generated by this App are not a substitute for professional veterinary care, consultation, diagnosis, or treatment. Always seek the advice of your veterinarian or other qualified animal health provider with any questions you may have regarding your pet's health, nutrition, or medical condition.
              </p>

              <p className="font-semibold">NO LIABILITY</p>
              <p>
                The creator, developer, owner, and operator of this App (collectively, the "Creator") shall not be held liable, responsible, or accountable in any way, shape, or form for any damages, losses, injuries, illnesses, adverse health effects, or any other consequences whatsoever that may arise from your use of this App or reliance on any information, analysis, recommendations, or content provided herein.
              </p>

              <p className="font-semibold">LIMITATION OF LIABILITY</p>
              <p>
                To the maximum extent permitted by applicable law, in no event shall the Creator be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Your use or inability to use the App</li>
                <li>Any content obtained from the App</li>
                <li>Unauthorized access to or alteration of your data</li>
                <li>Any other matter relating to the App</li>
              </ul>

              <p className="font-semibold">ACCURACY OF INFORMATION</p>
              <p>
                While we strive to provide accurate and up-to-date information, the Creator makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained in the App for any purpose.
              </p>

              <p className="font-semibold">THIRD-PARTY LINKS AND PRODUCTS</p>
              <p>
                This App may contain links to third-party websites, products, or services (including but not limited to NuVet Plus, NuJoint DS, and other pet nutrition products). The Creator is not responsible for the content, accuracy, or practices of these third-party sites or products. Any purchase or interaction with third-party products is solely between you and that third party.
              </p>

              <p className="font-semibold">NO AFFILIATION DISCLAIMER</p>
              <p>
                References to specific brands, products, or services do not constitute or imply endorsement, recommendation, or guarantee of quality by the Creator, unless explicitly stated otherwise.
              </p>

              <p className="font-semibold">ASSUMPTION OF RISK</p>
              <p>
                You acknowledge that you are solely responsible for any decisions you make regarding your pet's nutrition, health, and care based on information from this App. You assume full responsibility for all risks associated with using this App and the information it provides.
              </p>

              <p className="font-semibold">INDEMNIFICATION</p>
              <p>
                You agree to indemnify, defend, and hold harmless the Creator from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising from your use of the App or violation of these terms.
              </p>

              <p className="font-semibold">MODIFICATIONS</p>
              <p>
                The Creator reserves the right to modify or discontinue the App at any time without notice. The Creator shall not be liable to you or any third party for any modification, suspension, or discontinuance of the App.
              </p>

              <p className="font-semibold">GOVERNING LAW</p>
              <p>
                These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.
              </p>

              <p className="font-bold text-center mt-6 text-base">
                BY CLICKING "I AGREE" BELOW, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THIS DISCLAIMER AND ALL TERMS HEREIN. IF YOU DO NOT AGREE, DO NOT USE THIS APP.
              </p>

              <div className="h-8"></div>
            </div>
          </div>

          {!hasScrolledToBottom && (
            <p className="text-sm text-orange-600 font-semibold text-center mb-2">
              ⬇️ Please scroll to the bottom to continue ⬇️
            </p>
          )}

          <Button
            onClick={onAccept}
            disabled={!hasScrolledToBottom}
            className={`w-full ${hasScrolledToBottom ? 'bg-blue-600 hover:bg-blue-700' : 'bg-gray-400'}`}
          >
            {hasScrolledToBottom ? 'I Agree - Continue to App' : 'Please Scroll to Bottom First'}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}